### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by miltontony** [kstateome/django-cas#29]
Hi,

Do you plan to release `django-cas` to pypi?

**Comment by dstegelman** [comment]
Probably not.  This CAS setup has some fairly specific implementations.  There are also a multitude of other CAS libraries available on Pypi and we don't want to flood it with multiple libraries.  That being said, if there is a strong support for it, we'll consider it.

**Comment by miltontony** [comment]
Thanks for the heads up.

**Comment by dstegelman** [comment]
Version 1.0.0 which was what is **currently** in master has been released on pypi.  I'll document more on this later.

https://pypi.python.org/pypi/django-cas-client/1.0.0
