### ISSUE TITLE
Callback does not work when only one method is defined

### ISSUE THREAD

**Issue by leleuj** [kstateome/django-cas#31]
I'm starting working on: https://github.com/kstateome/django-cas/issues/28 and for that, I only defined one callback:

```
CAS_RESPONSE_CALLBACKS = (
    'webapp.cas.callbackresponse'
)
```

In that case, I get a 500 error and the callback method is never called.

After a successful CAS authentication, from: https://github.com/kstateome/django-cas/blob/develop/cas/backends.py#L70, the `cas_response_callbacks` method is called: https://github.com/kstateome/django-cas/blob/develop/cas/utils.py#L6.
With only one callback method defined (like above), the `callbacks` property is strangely an array of all characters: ['w', 'e', 'b', 'a', 'p', 'p', '.', 'c', 'a', 's', '.', 'c', 'a', 'l', 'l', 'b', 'a', 'c', 'k', 'r', 'e', 's', 'p', 'o', 'n', 's', 'e'] and thus, the callback is never properly called.
With two callback methods defined or more, it works.

**Comment by adongy** [comment]
It expects a tuple, you provided ('webapp.cas.callbackresponse') (no ',' after the string), which is identical to 'webapp.cas.callbackresponse'. It unpacks the string, thus you get ['w', 'e', 'b', 'a', 'p', 'p', '.', 'c', 'a', 's', '.', 'c', 'a', 'l', 'l', 'b', 'a', 'c', 'k', 'r', 'e', 's', 'p', 'o', 'n', 's', 'e'].

Try again with
```
CAS_RESPONSE_CALLBACKS = (
    'webapp.cas.callbackresponse',
)
```

**Comment by leleuj** [comment]
You're right, it works. Sorry for the wrong issue.
