### ISSUE TITLE
Django 1.9 warning

### ISSUE THREAD

**Issue by dstegelman** [kstateome/django-cas#50]
RemovedInDjango19Warning: Model class cas.models.PgtIOU doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

RemovedInDjango19Warning: Model class cas.models.Tgt doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

**Comment by dstegelman** [comment]
This is caused by not including ```cas``` in the installed items list.

**Comment by varunagrawal** [comment]
What should be added to the installed apps list to get this to work?
