### ISSUE TITLE
How can i get the object:request to do some initialization for the login user

### ISSUE THREAD

**Issue by junmingmiss** [kstateome/django-cas#52]
I want to put some permissions in the session after the user finished the CAS authentication
so that i can show the permissions in the page:index.html 
I find the 'CAS_RESPONSE_CALLBACKS ' to define a callback function,but it seens not enough for me
i don't know the way to get the 'request',so that i can do...request.session["modules"] = utils.get_user_modules(user)

**Comment by dstegelman** [comment]
If you need to just do some work after a user logs in you can listen for the [user_logged_in()](https://docs.djangoproject.com/en/dev/ref/contrib/auth/#module-django.contrib.auth.signals) signal provided by ```django.contrib.auth.signals```.  Django Cas logs the user in after they successfully authenticate so this signal is still sent.
