### ISSUE TITLE
HTTPS Logout Bug

### ISSUE THREAD

**Issue by epicserve** [kstateome/django-cas#54]
It seems like when using HTTPS it doesn't display the correct url to click on the CAS site to log back in. For example if the site is https://example.com/ and you sign out the CAS site will display http://example.com/http://example.com/ for the link to click to log back in. Using https://ngrok.com/ so I could debug https locally, I was able to trace down where the bug happens. It seems like it happens in the `_redirect_url` function found in `cas/views.py`. I was able to get around the bug by adding the following settings:

```
CAS_IGNORE_REFERER = True
CAS_REDIRECT_URL = '/'
```

**Comment by dstegelman** [comment]
Sorry for taking so long to get to this, been fairly busy.

The ```redirect_url``` uses django's is_secure() on the request to determine http/https when creating URLs.  I'll play around with it and see if I can get tests to fail for this situation.

**Comment by dstegelman** [comment]
I am not able to reproduce this.

**Comment by epicserve** [comment]
@dstegelman, We're not using CAS anymore so I don't have an easy way to get your more details either.
