### ISSUE TITLE
Not redirecting to CAS

### ISSUE THREAD

**Issue by lujonathanh** [kstateome/django-cas#56]
Hello,

I am running on Django 1.9. Instead of redirecting to the CAS url, I just get the error page. I am attempting to access https://localhost:8000/accounts/login as defined in my urls.py:

Here is my urls.py:

```
urlpatterns = [
    url(r'^proctors/admin/', admin.site.urls),
    url(r'^coaches/login/$', 'django.contrib.auth.views.login', {'template_name':'loginform.html'}, name='login'),
    url(r'^coaches/', include('registration.urls')),
    url(r'^proctors/', include('grading.urls')),
    url(r'^proctors/progress/$', 'grading.views.progress', name='progress'),
    url(r'^accounts/login/$', 'cas.views.login', name='proctor_login'),
    url(r'^accounts/logout/$', 'cas.views.logout', name='proctor_logout'),
]
```

"Forbidden

You do not have staff privileges."

Here is my settings.py:

```
CAS_SERVER_URL = 'https://fed.princeton.edu/cas/'

CAS_RETRY_LOGIN = True

CAS_REDIRECT_URL = '/proctors/'

```

**Comment by dstegelman** [comment]
Typically, the Forbidden message crops up when you are authenticated, but don't have staff privileges see [this](https://github.com/kstateome/django-cas/blob/develop/cas/middleware.py#L63)
