### ISSUE TITLE
Keeping CAS and Django sessions in sync

### ISSUE THREAD

**Issue by chadgh** [kstateome/django-cas#63]
Is there any way to keep the CAS session and Django sessions in sync?

It seems like if I log into a Django project using CAS and I continue using the site (keeping the Django session active, not expiring), eventually I notice that the CAS session has expired.

This might be from my not understanding what CAS is doing or how the django-cas-client app is working, but it seems like I should be able to more closely link up or connect (sync) the single sign-on feature of CAS with Django. I guess this might also mean that if I log out of CAS somewhere else, I should be logged out of my Django app too.

**Comment by tadonis** [comment]
My understanding is that you should customize the Django session. If you set Django session alive time to 0, then the Django app will redirect to CAS server whenever a protected resource is accessed. If CAS TGC is still not expired, then CAS server will redirect to Django app with a ST, else authentication is required.

But we don't do this in most case. You can set Django session alive time to a appropriate time.

**Comment by chadgh** [comment]
Sounds good. I'll try that. Thanks.
